# Generated by Django 2.0.9 on 2019-03-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_personindexpage_introduction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personindexpage',
            options={'verbose_name': 'People Index'},
        ),
    ]
