# Generated by Django 2.0.9 on 2018-12-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personindexpage',
            name='listing_image',
        ),
        migrations.RemoveField(
            model_name='personindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='personindexpage',
            name='social_image',
        ),
        migrations.DeleteModel(
            name='PersonIndexPage',
        ),
    ]
