# Generated by Django 2.0.9 on 2018-12-21 13:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    replaces = [('people', '0002_auto_20181219_1722'), ('people', '0003_auto_20181220_1515')]

    dependencies = [
        ('people', '0001_initial'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personindexpage',
            name='listing_image',
        ),
        migrations.RemoveField(
            model_name='personindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='personindexpage',
            name='social_image',
        ),
        migrations.DeleteModel(
            name='PersonIndexPage',
        ),
        migrations.AlterField(
            model_name='personpage',
            name='biography',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title', icon='title', template='patterns/molecules/streamfield/blocks/heading_block.html')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.CharBlock(classname='title')), ('attribution', wagtail.core.blocks.CharBlock(required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('document', wagtail.core.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock()), ('title', wagtail.core.blocks.CharBlock(required=False))]))], blank=True),
        ),
    ]
