# Generated by Django 2.0.9 on 2019-01-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190104_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personpagepersontype',
            name='page',
        ),
        migrations.RemoveField(
            model_name='personpagepersontype',
            name='person_type',
        ),
        migrations.RemoveField(
            model_name='personpagephonenumber',
            name='page',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='website',
        ),
        migrations.DeleteModel(
            name='PersonType',
        ),
        migrations.DeleteModel(
            name='PersonPagePersonType',
        ),
        migrations.DeleteModel(
            name='PersonPagePhoneNumber',
        ),
    ]
