# Generated by Django 2.0.9 on 2018-12-20 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_licensesnippet'),
        ('images', '0002_customimage_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='utils.LicenseSnippet'),
        ),
    ]
