# Generated by Django 2.0.9 on 2018-12-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsindex',
            options={'verbose_name': 'Articles Index'},
        ),
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': 'Article'},
        ),
    ]
