# Generated by Django 2.0.9 on 2018-12-17 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181214_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='image_caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='introduction',
            field=models.TextField(blank=True, max_length=165),
        ),
        migrations.AlterField(
            model_name='newspageauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.PersonPage'),
        ),
        migrations.AlterField(
            model_name='newspageauthor',
            name='biography',
            field=models.CharField(blank=True, help_text="Use this field to override the author's biography on this article page.", max_length=255),
        ),
    ]
