# Generated by Django 2.0.9 on 2018-12-20 16:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_category'),
        ('news', '0004_auto_20181220_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='utils.Category', verbose_name='category')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='news.NewsPage')),
            ],
        ),
        migrations.RemoveField(
            model_name='newspagenewstype',
            name='news_type',
        ),
        migrations.RemoveField(
            model_name='newspagenewstype',
            name='page',
        ),
        migrations.DeleteModel(
            name='NewsType',
        ),
        migrations.DeleteModel(
            name='NewsPageNewsType',
        ),
    ]
