# Generated by Django 2.1.7 on 2019-03-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdocument',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
