# Generated by Django 2.1.7 on 2019-03-23 23:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('images', '0002_auto_20190322_2207'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('people', '0002_auto_20190323_2357'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('standardpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InformationPage',
            new_name='StandardPage',
        ),
        migrations.RenameModel(
            old_name='InformationPageAuthor',
            new_name='StandardPageAuthor',
        ),
        migrations.RenameModel(
            old_name='InformationPageRelatedPage',
            new_name='StandardPageRelatedPage',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='listing_image',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='social_image',
        ),
        migrations.DeleteModel(
            name='IndexPage',
        ),
    ]
