# Generated by Django 2.0.9 on 2019-01-08 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20190107_1643'),
        ('people', '0003_auto_20190104_1426'),
        ('standardpages', '0003_auto_20190104_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.PersonPage'),
        ),
        migrations.AddField(
            model_name='informationpage',
            name='biography',
            field=models.CharField(blank=True, help_text="Use this field to override the author's biography on this page.", max_length=255),
        ),
        migrations.AddField(
            model_name='informationpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
        migrations.AddField(
            model_name='informationpage',
            name='image_caption',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
