# Generated by Django 2.0.9 on 2019-03-16 12:09

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20190117_1323'),
        ('standardpages', '0004_auto_20190108_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationPageAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('biography', models.CharField(blank=True, help_text="Use this field to override the author's biography on this information page.", max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.PersonPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='informationpage',
            name='author',
        ),
        migrations.AddField(
            model_name='informationpageauthor',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='standardpages.InformationPage'),
        ),
    ]
