# Generated by Django 2.0.9 on 2018-12-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='footer_navigation',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='secondary_navigation',
        ),
    ]
