# Generated by Django 2.0.9 on 2018-12-13 13:10

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='footer_navigation',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='secondary_navigation',
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='footer_bottom_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Small print text at the bottom of all pages. Not required.'),
        ),
    ]
