# Generated by Django 2.0.9 on 2018-12-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('standardpages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='listing_image',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='social_image',
        ),
        migrations.DeleteModel(
            name='IndexPage',
        ),
    ]
