# Generated by Django 2.0.9 on 2018-12-21 13:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    replaces = [('standardpages', '0002_auto_20181219_1719'), ('standardpages', '0003_auto_20181219_1720'), ('standardpages', '0004_auto_20181220_1515'), ('standardpages', '0005_standardpagecategory')]

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('standardpages', '0001_initial'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('utils', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='listing_image',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='social_image',
        ),
        migrations.DeleteModel(
            name='IndexPage',
        ),
        migrations.AlterModelOptions(
            name='informationpage',
            options={'verbose_name': 'Standard Page'},
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title', icon='title', template='patterns/molecules/streamfield/blocks/heading_block.html')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.CharBlock(classname='title')), ('attribution', wagtail.core.blocks.CharBlock(required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('document', wagtail.core.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock()), ('title', wagtail.core.blocks.CharBlock(required=False))]))]),
        ),
        migrations.CreateModel(
            name='StandardPageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='utils.Category', verbose_name='category')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='standardpages.InformationPage')),
            ],
        ),
    ]
