# Generated by Django 2.0.9 on 2018-12-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standardpages', '0002_auto_20181219_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationpage',
            options={'verbose_name': 'Standard Page'},
        ),
    ]
