# Generated by Django 2.0.9 on 2019-01-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_licensesnippet_squashed_0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltoactionsnippet',
            name='image',
        ),
        migrations.DeleteModel(
            name='CallToActionSnippet',
        ),
    ]
