# Generated by Django 2.1.7 on 2019-03-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepagecategory',
            options={'verbose_name': 'Article category', 'verbose_name_plural': 'Article categories'},
        ),
    ]
