# Generated by Django 2.1.7 on 2019-03-24 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190322_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepage',
            old_name='image_caption',
            new_name='featured_image_caption',
        ),
    ]
