# Generated by Django 2.0.9 on 2018-12-14 18:21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('images', '0002_customimage_file_hash'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPageAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('biography', models.CharField(blank=True, help_text='Biography that appears on this article page.', max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.PersonPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='newsindex',
            options={'verbose_name': 'Articles Index'},
        ),
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': 'Article'},
        ),
        migrations.AlterModelOptions(
            name='newstype',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='newsindex',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newspage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='image_caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='newspagenewstype',
            name='news_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='news.NewsType', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='newspageauthor',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='news.NewsPage'),
        ),
    ]
