# Generated by Django 2.1.7 on 2019-03-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspage',
            old_name='image_caption',
            new_name='featured_image_caption',
        ),
    ]
