# Generated by Django 2.2.4 on 2019-09-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190830_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='summary',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
    ]
