# Generated by Django 2.0.9 on 2018-12-21 13:01

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    replaces = [('news', '0004_auto_20181220_1515'), ('news', '0005_auto_20181220_1638')]

    dependencies = [
        ('news', '0003_auto_20181217_1257'),
        ('utils', '0002_licensesnippet'),
        ('utils', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='utils.LicenseSnippet'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title', icon='title', template='patterns/molecules/streamfield/blocks/heading_block.html')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.CharBlock(classname='title')), ('attribution', wagtail.core.blocks.CharBlock(required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('document', wagtail.core.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock()), ('title', wagtail.core.blocks.CharBlock(required=False))]))]),
        ),
        migrations.CreateModel(
            name='NewsPageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='utils.Category', verbose_name='category')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='news.NewsPage')),
            ],
        ),
        migrations.RemoveField(
            model_name='newspagenewstype',
            name='news_type',
        ),
        migrations.RemoveField(
            model_name='newspagenewstype',
            name='page',
        ),
        migrations.DeleteModel(
            name='NewsType',
        ),
        migrations.DeleteModel(
            name='NewsPageNewsType',
        ),
    ]
