# Generated by Django 2.1.7 on 2019-03-22 12:33

from django.db import migrations, models
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190322_1233'),
        ('news', '0006_auto_20190317_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspageauthor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='newspageauthor',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='newsindex',
            options={'verbose_name': 'News Index'},
        ),
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newspagecategory',
            options={'verbose_name': 'News category', 'verbose_name_plural': 'News categories'},
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='license',
        ),
        migrations.RemoveField(
            model_name='newspagecategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newspagecategory',
            name='page',
        ),
        migrations.AddField(
            model_name='newspage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='articles.ArticlePageCategory'),
        ),
        migrations.AddField(
            model_name='newspagecategory',
            name='name',
            field=models.CharField(default='asdf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspagecategory',
            name='slug',
            field=models.SlugField(default='asdf', max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.DeleteModel(
            name='NewsPageAuthor',
        ),
    ]
