# Generated by Django 2.1.7 on 2019-03-22 12:43

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190322_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='news.NewsPageCategory'),
        ),
    ]
