# Generated by Django 2.1.7 on 2019-03-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20190322_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='introduction',
            field=models.TextField(max_length=165),
        ),
    ]
