# Generated by Django 2.0.9 on 2018-12-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('version', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=255)),
            ],
        ),
    ]
