# Generated by Django 2.0.9 on 2018-12-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_licensesnippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
