# Generated by Django 2.1.7 on 2019-03-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190322_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='author',
            field=models.CharField(blank=True, max_length=165, null=True),
        ),
    ]
