# Generated by Django 2.0.9 on 2019-03-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20190107_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='author',
            field=models.TextField(blank=True, max_length=165, null=True),
        ),
    ]
