# Generated by Django 2.0.9 on 2019-03-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_BE'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='button_link',
            new_name='hero_button_link',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='button_text',
            new_name='hero_button_text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='introduction',
            new_name='hero_introduction',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
