# Generated by Django 2.1.7 on 2019-03-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepagefeaturedpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagefeaturedpage',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagefeaturedpage',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
