# Generated by Django 2.1.7 on 2019-03-22 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0005_auto_20190316_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='articles_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='articles_text',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_text',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pages_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pages_text',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
