# Generated by Django 2.1.7 on 2019-03-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190324_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagefeaturedpage',
            name='text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
