# Generated by Django 2.1.7 on 2019-03-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190322_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='articles_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='news_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='pages_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
