# Generated by Django 2.1.7 on 2019-03-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190322_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='articles_linktext',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_linktext',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pages_linktext',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
