# Generated by Django 2.1.7 on 2019-03-24 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190324_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagefeaturedpage',
            old_name='text',
            new_name='summary',
        ),
    ]
