# Generated by Django 2.0.9 on 2018-12-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='call_to_action',
        ),
    ]
