# Generated by Django 2.0.9 on 2019-01-24 14:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20190107_1643'),
        ('standardpages', '0004_auto_20190108_1308'),
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0003_remove_homepage_call_to_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageFeaturedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='standardpages.InformationPage', verbose_name='featured page')),
            ],
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='strapline',
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_text',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='images.CustomImage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='introduction',
            field=models.CharField(default='Introduction text', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagefeaturedpage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_pages', to='home.HomePage'),
        ),
    ]
